### ISSUE TITLE
Install fails with "ImportError: No module named future.moves.urllib.request"

### ISSUE THREAD

**Issue by ebogart** [slinderman/pypolyagamma#11]
Installing from pypi with "pip install pypolyagamma" leads to the above error for me in environments without the future package installed, across multiple machines and platforms. 

Installing the future package first resolves this, so there's an easy workaround, of course.

I thought this was because the version on PyPI doesn't include #8 but cloning the repository in a fresh environment and running "pip install -e ." leads to the same message, so that may not be the problem.

(Thanks for making this package available, it's been very helpful!)

**Comment by slinderman** [comment]
Ugh, more frustration with `setup_requires`.  I've taken the easy road and switched to an admittedly hackier approach: we'll just try importing the python2 version (from `urllib`) and then the python 3 version (from `urllib.request`) if that fails.  I've pushed this change (https://github.com/slinderman/pypolyagamma/commit/5c9fce56db71a84fba41b82d95ae180c07441d27) and uploaded a new version to pypi.  

Can you please test and see if it works for you now?

**Comment by ebogart** [comment]
Thanks! Installing from pypi in an environment without future now works for me, so long as numpy is already installed.

If numpy is not installed, the call to np.get_include() leads to a NameError. I'm not sure why having numpy in setup_requires doesn't fix this, and I'm not sure how important it is to support the case where numpy isn't already installed, but I believe #12 will do that.

**Comment by ebogart** [comment]
In any event, this particular issue is now resolved; thank you very much!
